# Generated by Django 4.1.1 on 2022-11-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='videothumbnail')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videofile')),
                ('desc', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userchannel')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislike', to='account.userchannel')),
                ('likes', models.ManyToManyField(blank=True, related_name='like', to='account.userchannel')),
            ],
        ),
    ]
